spring.application.name=artist-portfolio-server
springdoc.swagger-ui.path=/swagger-ui.html

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=86400000

nominatim.base-url=https://nominatim.openstreetmap.org
app.base-url=${APP_BASE_URL:https://artist-portfolio-server.fly.dev}